- name: Config Vim with plugins
  hosts: localhost
  gather_facts: yes
  become: no
  vars: 
    vim_dir: "{{ ansible_env.HOME }}/.vim"
    vimrc: "{{ ansible_env.HOME }}/.vimrc"
    it_basic_vimrc: "{{ ansible_env.PWD }}/it-basic.vimrc"
  tasks: 
  - name: Install reguired packages
    apt:
      pkg: 
        - git
        - build-essential
        - cmake
        - python3-dev
      state: present
      update_cache: yes
    become: yes

  - name: Ensure .vim/{autoload, backup, colors, plugged} directory exists
    file:
      path: "{{ item }}"
      state: directory
      recurse: no
      mode: 0750
    loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/autoload"
        - "{{ vim_dir }}/backup"
        - "{{ vim_dir }}/colors"
        - "{{ vim_dir }}/plugged"

  - name: Ensure Plug is in place
    get_url:
      dest: "{{ vim_dir }}/autoload/plug.vim"
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  - name: Ensure .vimrc config in place (prefer to create a link)
    file:
      src: "{{ it_basic_vimrc }}"
      dest: "{{ vimrc }}"
      state: link
      mode: '0644'

  - name: Install all Plugins from .vimrc using :PlugInstall
    shell: vim +'PlugInstall --sync' +qa
    args:
      executable: /bin/bash

  - name: Compile YCM server (by running a py script)
    shell: python3 "{{ vim_dir }}/plugged/YouCompleteMe/install.py"
    args:
      executable: /bin/bash

